### ISSUE TITLE
Enhancement - Option to suppress H3 title in HTML

### ISSUE THREAD

**Issue by jeremyregnerus** [death-save/pin-cushion#13]
I'm not sure if this is warranted or not. But would it be possible to add an option to suppress the h3 header in the Pin Cushion on hover text? 
I already included h2 headers in most of my journal entries. This creates a double header for pin cushion hover text. First an h3, then my h2. I can easily remove the html whenever I update pin cushion and this is really just a qol thing for me; but thought others may want to suppress the header as well.

**Comment by jeremyregnerus** [comment]
I have no idea why the text is bold above

**Comment by eclarke12** [comment]
I'll tackle this when I add more granular "per JournalEntry" settings for Pin Cushion
