### ISSUE TITLE
On first load all pins are hidden due to a bug in hover logic

### ISSUE THREAD

**Issue by eclarke12** [death-save/pin-cushion#18]

**Comment by highnrgappalachian** [comment]
This is a fairly annoying bug, any plans on fixing it soon?

**Comment by eclarke12** [comment]
It's super annoying I know! I will try to have a look this week and assess
how easy a fix is. Sorry for the inconvenience it causes! As a workaround:
navigating away and then back to the current scene should fix it.

**Comment by highnrgappalachian** [comment]
Yes, I was aware of the workaround. Thanks for taking a look, much appreciated!

**Comment by eclarke12** [comment]
@highnrgappalachian do you use GM Scene Background? In my investigation I found this bug seemed to be caused there instead. I pushed an update for GM Scene Background that should resolve the issue.

**Comment by highnrgappalachian** [comment]
Yes, I do use GM Scene Background! I wonder if some fog problems I was having were due to that!

**Comment by eclarke12** [comment]
If the issue is resolved by the GM Scene Background update, please let me
know or close this issue, thanks!

**Comment by highnrgappalachian** [comment]
Right. Just tested with the new GM Scene Background update, you can consider this fixed.
