### ISSUE TITLE
Allow Users (other than GM) to create Pins on scenes. (Willing to commission)

### ISSUE THREAD

**Issue by tmtProdigy** [death-save/pin-cushion#32]
By default in Foundry  "Note" extends "PlaceableObject" and the "_canCreate" method of "PlaceableObject" is a boolean set as "user.isGM", so Note seems to require GM privs to create. 

To enable players to create notes as well (specifically for scenes world maps, such as in a westmarches-style game) an inbuilt option would be great. 

Some ideas from users in discord were: 
1. Perhaps the module could use sockets to get around this
2. Why not just "PlayerNote" extends "Note", then override "_canCreate"?

Thanks for looking into this, you can contact me via foundry discord @tmtprodigy
Cheers!

**Comment by eclarke12** [comment]
Solution Design idea 1:
1. Create a new extended class PlayerNote
2. Override _canCreate
3. On double-click create relevant JE
4. determine the executing user
5. Defer execution to the correct Note class

**Comment by eclarke12** [comment]
Add a setting "Default Player Note Permission for Other Users": None, Limited, Observer, Owner

**Comment by eclarke12** [comment]
Just an update on this, it is being addressed by #35 thanks to @ethaks !

**Comment by apoapostolov** [comment]
What permission is needed for user to make notes? I get constantly warning that player cannot create Note.

**Comment by eclarke12** [comment]
> What permission is needed for user to make notes? I get constantly warning that player cannot create Note.

this functionality is not released yet... stay tuned for version 1.2!
