### ISSUE TITLE
Player lacks permission to create a journal

### ISSUE THREAD

**Issue by franckflo** [death-save/pin-cushion#44]
When a player tries to create a Pin by double-clicking on the map, the error mentioned in this issue's title pops-up. There is a folder created automatically in the Journal tab, with the player name. I tried granting owner permission to the folder, but I'm not sure it worked. I did set the Module settings to give Owner permissions to the new journal entry as well. Is there something else I need to do to make it work? 

Settings
![Pin CuShion](https://user-images.githubusercontent.com/80221412/112778562-ab63b880-8ff9-11eb-90c8-dbd677b1b6e9.png)

Error: 
![Pin Cushion](https://user-images.githubusercontent.com/80221412/112778169-c2ee7180-8ff8-11eb-8dbe-fbcd2edbdee4.png)

**Comment by eclarke12** [comment]
You need to grant them the core permission to create Journal Entries.
