### ISSUE TITLE
V9 Update or Abandoned?

### ISSUE THREAD

**Issue by PhluXx1** [death-save/pin-cushion#77]
This is a really great module and it's used a lot in my campaign. I'm sure a lot of us are hoping to see a V9 update or to know if this module been abandoned? If we are getting an update when can we expect it?

**Comment by Ethaks** [comment]
The module has not been abandoned, and there *will* be a V9 compatible update. As to when, it should be soon™ – I'll take another look at the existing PR(s) as soon as I'm done diligently nurturing my cold.
