### ISSUE TITLE
Pin Labels not showing on hover

### ISSUE THREAD

**Issue by DOMtheDM** [death-save/pin-cushion#82]
When only Pin Cushion module is active, my map pins don't show their referenced journal names (or text label) when I hover over them. It also doesn't show the names when you hold alt. I discovered that if you have "Enable feature Backgroundless Pins" checked off in the module settings and you open up the Map Note configuration menu for one of the map pins and then click "Update Map Note", even if you didn't change anything in the settings then the name will start appearing on hover. But if the feature is unchecked, nothing you do will make the name appear on hover. 

Super weird issue but I'm thinking maybe it has to do with the backgroundless pin feature since it was recently added?

**Comment by Havoclivekiller** [comment]
Can confirm. Some compatibility got broken and Pin Cushion breaks Pins.

**Comment by p4535992** [comment]
@DOMtheDM @Havoclivekiller Excuse me just for clarity, if you are using my fork (specify the module version for security), open these issues on my fork (so we don't disturb Death Save).
